apiVersion: v1
kind: Secret
metadata:
  name: l1-monitoring-secrets
type: Opaque
stringData:
  postgres-db: postgres
  postgres-user: postgres
  postgres-password: postgres
  clickhouse-user: default
  clickhouse-password: ""
  ollama-api-key: ""
  app-secret-key: l1monitoringsecretkey