#!/bin/bash
# Manual steps for deploying the v2 versions without deleting existing deployments

echo "This script will show you the manual commands to run, but will not execute them automatically."
echo "Copy and paste each command as needed."
echo ""
echo "1. First, check what resources currently exist:"
echo "   kubectl get deployments"
echo "   kubectl get services"
echo "   kubectl get pods"
echo ""
echo "2. Apply the secrets first:"
echo "   kubectl apply -f k8s/secrets/secrets.yaml"
echo ""
echo "3. Apply the individual v2 deployments:"
echo "   # Ollama v2"
echo "   kubectl apply -f k8s/deployments/ollama-v2-deployment.yaml"
echo "   kubectl apply -f k8s/services/ollama-service.yaml"
echo ""
echo "   # Postgres v2"
echo "   kubectl apply -f k8s/deployments/postgres-v2-deployment.yaml"
echo "   kubectl apply -f k8s/services/postgres-service.yaml"
echo ""
echo "   # ClickHouse v2"
echo "   kubectl apply -f k8s/deployments/clickhouse-v2-deployment.yaml"
echo "   kubectl apply -f k8s/services/clickhouse-service.yaml"
echo ""
echo "   # Main app v2"
echo "   kubectl apply -f k8s/deployments/app-v2-deployment.yaml"
echo "   kubectl apply -f k8s/services/app-service.yaml"
echo ""
echo "4. Or apply everything at once with the combined file:"
echo "   kubectl apply -f k8s/deployment-all-v2.yaml"
echo ""
echo "5. Check the status of the new deployments:"
echo "   kubectl get deployments"
echo "   kubectl get pods -o wide"
echo "   kubectl get services"
echo ""
echo "6. If you want to delete the old deployments after confirming the new ones work:"
echo "   kubectl delete deployment ollama"
echo "   kubectl delete deployment l1-monitoring"
echo "   kubectl delete deployment clickhouse"
echo "   kubectl delete deployment postgres"
echo ""
echo "7. To troubleshoot specific pods:"
echo "   kubectl describe pod <pod-name>"
echo "   kubectl logs <pod-name>"
echo ""
echo "Remember: The v2 deployments can run alongside the original ones since they have different names."
echo "This approach avoids the 'not found' errors when deleting non-existent deployments."